name: CloudShop CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: cloudshop-dev-api

jobs:
  build-and-push:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # GitHub OIDC -> AWS STS -> Temporary Credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::089959489412:role/CloudShop-GitHubActions-ECR-Role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # Temporary AWS credentials -> ECR authorization token -> Docker login
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          echo "Building $IMAGE_URI"

          docker build \
            -t "$IMAGE_URI" \
            ./backend

          docker push "$IMAGE_URI"

          echo "IMAGE_URI=$IMAGE_URI" >> "$GITHUB_ENV"

      - name: Show deployed image
        run: echo "$IMAGE_URI"